# Generated by Django 5.0.4 on 2024-06-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=50)),
                ('horaInicioTest', models.DateTimeField()),
                ('horaFinTest', models.DateTimeField()),
                ('horaInicioPro', models.DateTimeField()),
                ('horaFinPro', models.DateTimeField()),
            ],
        ),
    ]
